"""BlendQueue smoke test against the local server (which must be running).

    tests\run_smoke.bat quick        renders a short EEVEE sequence
    tests\run_smoke.bat multi        checks scene selection (-S)
    tests\run_smoke.bat cycles       Cycles render on the GPU
    tests\run_smoke.bat format       format overrides: EXR, video, mixed queue
    tests\run_smoke.bat script       per-job Python scripts
    tests\run_smoke.bat overwrite    existing frames: skip or overwrite
    tests\run_smoke.bat real "G:/path/file.blend" [render]

The test .blend files are generated by tests/make_tests.py with Blender.
"""
import json
import os
import sys
import time
import urllib.error
import urllib.request

BASE = os.environ.get("BLENDQUEUE_URL", "http://127.0.0.1:8777")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTS = os.path.join(ROOT, "data", "tests").replace("\\", "/")


def req(method, path, body=None, timeout=180):
    data = json.dumps(body).encode("utf-8") if body is not None else None
    r = urllib.request.Request(BASE + path, data=data, method=method,
                               headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(r, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def find(d, key, iid):
    return next((x for x in d.get(key, []) if x.get("id") == iid), None)


def wait_file(fid, timeout=900):
    t0 = time.time()
    while time.time() - t0 < timeout:
        f = find(req("GET", "/api/state"), "files", fid)
        if f and f.get("status") in ("ready", "error"):
            return f
        time.sleep(2)
    return None


def wait_job(jid, timeout=2400):
    t0, last = time.time(), ""
    while time.time() - t0 < timeout:
        j = find(req("GET", "/api/state"), "jobs", jid)
        if j:
            p = j.get("progress") or {}
            line = "{} {:.0%} {}".format(j["status"], p.get("percent") or 0, p.get("message") or "")
            if line != last:
                print("    " + line, flush=True)
                last = line
            if j["status"] in ("done", "error", "canceled"):
                return j
        time.sleep(2)
    return None


def add_and_inspect(path):
    print("== add:", path)
    r = req("POST", "/api/files/add", {"paths": [path]})
    fid = r["added"][0]["id"]
    f = wait_file(fid)
    if not f or f.get("status") != "ready":
        print("INSPECTION FAILED:", (f or {}).get("inspect_error"))
        return None
    rep = f["report"]
    print("   inspection OK in", rep.get("inspect_seconds"), "s | saved with Blender",
          rep.get("saved_with"), "| missing external:", rep.get("missing_external_count"))
    for s in rep.get("scenes", []):
        print("    - {} | frames {}-{} ({}) | {} {} | {}x{} | cam {} | out {} -> {}".format(
            s["name"], s["frame_start"], s["frame_end"], s["frame_count"],
            s.get("engine"), s.get("samples") or "", s.get("resolution_x"), s.get("resolution_y"),
            s.get("camera"), s.get("filepath_raw"), s.get("filepath_abs")))
    return {"id": fid, "report": rep}


def enqueue(file_id, scene, out_dir, extra=None, frames=None):
    ov = {"output_dir": out_dir}
    if extra:
        ov.update(extra)
    body = {"file_id": file_id, "scene": scene["name"], "overrides": ov}
    fr = frames or {"start": scene["frame_start"], "end": scene["frame_end"]}
    body["frames"] = fr
    print("== queue:", scene["name"], "frames", fr, "->", out_dir)
    r = req("POST", "/api/jobs", body)
    jid = r["job"]["id"]
    j = wait_job(jid)
    if not j:
        print("    TIMEOUT waiting for the job")
        return None
    print("    status:", j["status"], "| duration:", j.get("duration_s"), "s | outputs:",
          len(j.get("outputs") or []), "| preview:", (j.get("preview") or {}).get("video"))
    if j.get("error"):
        print("    error:", str(j["error"])[:400])
    for p in (j.get("outputs") or [])[:4]:
        print("      ·", p)
    return j


def mode_quick():
    info = add_and_inspect(TESTS + "/quick.blend")
    if not info:
        return False
    j = enqueue(info["id"], info["report"]["scenes"][0], TESTS + "/renders/quick_eevee")
    return bool(j and j["status"] == "done")


def mode_multi():
    info = add_and_inspect(TESTS + "/multi.blend")
    if not info:
        return False
    scenes = info["report"]["scenes"]
    if len(scenes) < 2:
        print("FAILED: expected 2 scenes, found", len(scenes))
        return False
    j = enqueue(info["id"], scenes[1], TESTS + "/renders/multi")
    if j and j.get("outputs"):
        ok = any("EscenaB" in str(p) for p in j["outputs"])
        print("    scene selection (-S EscenaB):", "YES" if ok else "NO")
        return ok and j["status"] == "done"
    return False


def mode_cycles():
    info = add_and_inspect(TESTS + "/quick_cycles.blend")
    if not info:
        return False
    j = enqueue(info["id"], info["report"]["scenes"][0], TESTS + "/renders/cycles",
                extra={"device": "GPU", "samples": 16})
    return bool(j and j["status"] == "done")


def mode_real(args):
    path = args[0]
    info = add_and_inspect(path)
    if not info:
        return False
    if "render" not in args:
        return True
    scenes = info["report"]["scenes"]
    if not scenes:
        return False
    s = scenes[0]
    j = enqueue(info["id"], s, TESTS + "/renders/real",
                extra={"device": "GPU", "samples": 24},
                frames={"start": s["frame_start"], "end": s["frame_start"]})
    return bool(j and j["status"] == "done")


def req_status(method, path, body=None):
    """Like req() but returns (status, json) instead of raising on HTTP errors."""
    data = json.dumps(body).encode("utf-8") if body is not None else None
    r = urllib.request.Request(BASE + path, data=data, method=method,
                               headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(r, timeout=120) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        return exc.code, json.loads(exc.read().decode("utf-8") or "{}")


def mode_format():
    """Output format overrides: EXR, video and editing the queue."""
    ok = True

    def check(name, cond, detail=""):
        nonlocal ok
        print(("    OK   " if cond else "    FAILED") + " " + name +
              ((" -> " + str(detail)) if detail else ""))
        ok = ok and bool(cond)

    info = add_and_inspect(TESTS + "/quick.blend")
    if not info:
        return False
    scene = info["report"]["scenes"][0]
    caps = info["report"].get("capabilities") or {}
    check("the report carries the scene format", bool(scene.get("file_format")),
          scene.get("file_format"))
    check("the report carries Blender's formats", len(caps.get("file_format") or []) > 5,
          len(caps.get("file_format") or []))
    cat = req("GET", "/api/formats")
    check("the catalog comes from Blender", cat.get("source") == "blender", cat.get("source"))

    print("== edit the format of a queued job")
    req("POST", "/api/queue/pause", {"paused": True})
    jid = req("POST", "/api/jobs", {"file_id": info["id"], "scene": scene["name"],
                                    "frames": {"start": 1, "end": 1},
                                    "overrides": {"output_dir": TESTS + "/renders/format"}})["job"]["id"]
    st, r = req_status("PATCH", "/api/jobs/" + jid,
                       {"overrides": {"output_dir": TESTS + "/renders/format", "format": "FFMPEG",
                                      "ffmpeg_container": "MKV", "exr_codec": "ZIP"}})
    ov = (r.get("job") or {}).get("overrides") or {}
    check("PATCH applies the format", ov.get("format") == "FFMPEG", ov)
    check("PATCH drops what does not apply", "exr_codec" not in ov, ov)
    check("PATCH keeps the folder", bool(ov.get("output_dir")), ov)
    r = req("POST", "/api/jobs/format", {"format": "PNG", "color_depth": "16"})
    check("apply to the whole queue", jid in (r.get("changed") or []), r.get("changed"))
    req("DELETE", "/api/jobs/" + jid)
    req("POST", "/api/queue/pause", {"paused": False})

    print("== render forcing OpenEXR")
    j = enqueue(info["id"], scene, TESTS + "/renders/format",
                extra={"format": "OPEN_EXR", "color_depth": "16", "exr_codec": "ZIP", "samples": 8},
                frames={"start": 1, "end": 2})
    outs = (j or {}).get("outputs") or []
    check("render OK", bool(j and j["status"] == "done"), (j or {}).get("error"))
    check("writes .exr", bool(outs) and all(p.lower().endswith(".exr") for p in outs), outs[:2])

    print("== render forcing video (FFmpeg/MKV)")
    j = enqueue(info["id"], scene, TESTS + "/renders/format",
                extra={"format": "FFMPEG", "ffmpeg_container": "MKV", "ffmpeg_codec": "H264",
                       "samples": 8},
                frames={"start": 1, "end": 4})
    outs = (j or {}).get("outputs") or []
    check("video render OK", bool(j and j["status"] == "done"), (j or {}).get("error"))
    check("a single .mkv", len(outs) == 1 and outs[0].lower().endswith(".mkv"), outs)
    return ok


def png_size(path):
    """Width/height read from the PNG's IHDR header."""
    with open(path, "rb") as fh:
        d = fh.read(33)
    assert d[1:4] == b"PNG", "no es PNG"
    return int.from_bytes(d[16:20], "big"), int.from_bytes(d[20:24], "big")


def mode_script():
    """Per-job Python scripts: library, real effect, frozen copy and failure."""
    ok = True

    def check(name, cond, detail=""):
        nonlocal ok
        print(("    OK   " if cond else "    FAILED") + " " + name +
              ((" -> " + str(detail)) if detail else ""))
        ok = ok and bool(cond)

    info = add_and_inspect(TESTS + "/quick.blend")
    if not info:
        return False
    scene = info["report"]["scenes"][0]
    out_dir = TESTS + "/renders/script"

    print("== script library")
    st, r = req_status("POST", "/api/scripts",
                       {"name": "Media resolucion", "code": "sc.render.resolution_percentage = 50"})
    check("create script", st == 200 and r.get("script", {}).get("id"), (st, r))
    sid = (r.get("script") or {}).get("id")
    if not sid:
        return False
    check("shows up in the state",
          any(x["id"] == sid for x in req("GET", "/api/state").get("scripts", [])))

    print("== the script really changes the render")
    j = enqueue(info["id"], scene, out_dir, extra={"script_id": sid}, frames={"start": 1, "end": 1})
    outs = (j or {}).get("outputs") or []
    check("render OK", bool(j and j["status"] == "done"), (j or {}).get("error"))
    check("the job stores the script name",
          (j or {}).get("overrides", {}).get("script_name") == "Media resolucion",
          (j or {}).get("overrides"))
    if outs:
        size = png_size(outs[0])
        check("resolution halved (160x90)", size == (160, 90), size)
    else:
        check("there is output", False)

    print("== frozen copy: editing the library does not touch queued jobs")
    req("POST", "/api/queue/pause", {"paused": True})
    jid = req("POST", "/api/jobs", {"file_id": info["id"], "scene": scene["name"],
                                    "frames": {"start": 1, "end": 1},
                                    "overrides": {"output_dir": out_dir, "script_id": sid}})["job"]["id"]
    req("PATCH", "/api/scripts/" + sid, {"code": "sc.render.resolution_percentage = 25"})
    ov = find(req("GET", "/api/state"), "jobs", jid)["overrides"]
    check("the queued job keeps its copy", "50" in (ov.get("script") or ""), ov.get("script"))
    req("DELETE", "/api/jobs/" + jid)

    print("== a broken script leaves the job in error")
    sid2 = req("POST", "/api/scripts", {"name": "Roto", "code": "raise RuntimeError('boom de prueba')"})["script"]["id"]
    req("POST", "/api/queue/pause", {"paused": False})
    j = enqueue(info["id"], scene, out_dir, extra={"script_id": sid2}, frames={"start": 1, "end": 1})
    check("the job fails", bool(j and j["status"] == "error"), (j or {}).get("status"))
    log = req("GET", "/api/jobs/" + j["id"] + "/log?tail=400")["log"] if j else ""
    check("the traceback lands in the log", "boom de prueba" in log, log[-160:])
    check("the job error shows the exception, not 'Blender quit'",
          "boom de prueba" in str((j or {}).get("error")), (j or {}).get("error"))
    check("it wrote no outputs", not (j or {}).get("outputs"), (j or {}).get("outputs"))

    for x in (sid, sid2):
        req_status("DELETE", "/api/scripts/" + x)
    check("delete from the library",
          not any(y["id"] in (sid, sid2) for y in req("GET", "/api/state").get("scripts", [])))
    return ok


def mode_overwrite():
    """Existing frames: preflight, skipping them, and forcing the overwrite."""
    ok = True

    def check(name, cond, detail=""):
        nonlocal ok
        print(("    OK   " if cond else "    FAILED") + " " + name +
              ((" -> " + str(detail)) if detail else ""))
        ok = ok and bool(cond)

    info = add_and_inspect(TESTS + "/quick.blend")
    if not info:
        return False
    scene = info["report"]["scenes"][0]
    check("the report says whether the scene overwrites",
          "use_overwrite" in scene, scene.get("use_overwrite"))
    out_dir = TESTS + "/renders/overwrite"
    frames = {"start": 1, "end": 2}
    body = {"file_id": info["id"], "scene": scene["name"], "frames": frames,
            "overrides": {"output_dir": out_dir}}

    print("== nothing on disk yet")
    pre = req("POST", "/api/jobs/preflight", body)
    check("preflight finds nothing", pre["existing"] == 0, pre)
    check("preflight resolves the folder", bool(pre["folder"]), pre["folder"])

    j = enqueue(info["id"], scene, out_dir, frames=frames)
    check("first render writes files", bool(j and len(j.get("outputs") or []) == 2),
          len((j or {}).get("outputs") or []))
    first = {p: os.path.getmtime(p) for p in (j.get("outputs") or [])}

    print("== the frames are there now")
    pre = req("POST", "/api/jobs/preflight", body)
    check("preflight counts them", pre["existing"] == 2, pre["existing"])
    check("preflight shows examples", bool(pre["examples"]), pre["examples"])

    print("== queueing with Skip existing renders nothing")
    j = enqueue(info["id"], scene, out_dir, extra={"overwrite": False}, frames=frames)
    check("job is done", bool(j and j["status"] == "done"), (j or {}).get("status"))
    check("no outputs", not (j or {}).get("outputs"), (j or {}).get("outputs"))
    check("and it says why", "skipped" in str((j or {}).get("note") or "").lower(),
          (j or {}).get("note"))

    print("== queueing with Overwrite renders them again")
    time.sleep(1.1)                      # so mtime can differ
    j = enqueue(info["id"], scene, out_dir, extra={"overwrite": True}, frames=frames)
    outs = (j or {}).get("outputs") or []
    check("writes the files again", len(outs) == 2, outs)
    check("they were really rewritten",
          all(os.path.getmtime(p) > first.get(p, 0) for p in outs if p in first), outs)
    check("no leftover note", not (j or {}).get("note"), (j or {}).get("note"))
    return ok


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    mode = sys.argv[1]
    st = req("GET", "/api/state")
    print("current state: files =", len(st["files"]), "| jobs =", len(st["jobs"]),
          "| blender:", (st.get("blender") or {}).get("version"))
    ok = False
    if mode == "quick":
        ok = mode_quick()
    elif mode == "multi":
        ok = mode_multi()
    elif mode == "cycles":
        ok = mode_cycles()
    elif mode == "format":
        ok = mode_format()
    elif mode == "script":
        ok = mode_script()
    elif mode == "overwrite":
        ok = mode_overwrite()
    elif mode == "real":
        if len(sys.argv) < 3:
            print("missing the .blend path")
            return 1
        ok = mode_real(sys.argv[2:])
    else:
        print("unknown mode:", mode)
        return 1
    print("RESULT:", "OK" if ok else "FAILED")
    return 0 if ok else 2


if __name__ == "__main__":
    sys.exit(main())
